# Generated by Django 5.2.12 on 2026-03-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("ADMINISTRATIVO", "Administrativo"),
                    ("MEDICO", "Médico"),
                    ("ESPECIALISTA", "Especialista"),
                    ("ADMIN", "Admin del Sistema"),
                ],
                max_length=20,
            ),
        ),
    ]
