# Generated by Django 5.2.12 on 2026-05-31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=60, unique=True)),
                ('especialidad_principal', models.CharField(max_length=120)),
                ('subespecialidad', models.CharField(blank=True, max_length=120, null=True)),
                ('anios_experiencia', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                (
                    'id_usuario',
                    models.OneToOneField(
                        db_column='id_usuario',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='perfil_medico',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'medicos',
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['id_usuario__apellidos', 'id_usuario__nombres'],
            },
        ),
    ]
