# Generated by Django 5.2.13 on 2026-04-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cita",
            new_name="citas_id_espe_26b5de_idx",
            old_name="citas_id_esp_fecha_h_80f8ff_idx",
        ),
        migrations.RenameIndex(
            model_name="cita",
            new_name="citas_id_paci_b602f9_idx",
            old_name="citas_id_pac_fecha_h_56b320_idx",
        ),
        migrations.RenameIndex(
            model_name="cita",
            new_name="citas_estado_5699c4_idx",
            old_name="citas_estado_fecha_h_4673bf_idx",
        ),
    ]
